/**
 * Bootstrap Template for To-Do HQ
 * 
 * This template contains initial epics and tasks representing features
 * that need work to reach 100% completion. Based on the Features Map.
 */

type EpicStatus = 'not_started' | 'in_progress' | 'completed' | 'on_hold';
type TaskStatus = 'todo' | 'in_progress' | 'done' | 'cancelled';
type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

interface TaskTemplate {
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  sortOrder: number;
  tags?: string[];
  notes?: string;
}

interface EpicTemplate {
  name: string;
  description?: string;
  status: EpicStatus;
  targetCompletionPercent: number;
  sortOrder: number;
  tags?: string[];
  tasks: TaskTemplate[];
}

interface BootstrapTemplate {
  epics: EpicTemplate[];
}

export const BOOTSTRAP_TEMPLATE: BootstrapTemplate = {
  epics: [
    // CORE PLATFORM FEATURES
    {
      name: 'Dashboard',
      description: 'Real-time agent monitoring and activity feed',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 1,
      tags: ['core', 'dashboard'],
      tasks: [
        {
          title: 'Stats with trend indicators',
          description: 'Percentage change, visual arrows, color coding',
          status: 'done',
          priority: 'high',
          sortOrder: 1,
          tags: ['stats', 'trends', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint',
        },
        {
          title: 'Activity feed polish',
          description: 'Infinite scroll, filters by type, mark as read',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['activity', 'ui', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint',
        },
        {
          title: 'Data tables enhancement',
          description: 'Advanced filtering, bulk operations, column customization',
          status: 'done',
          priority: 'high',
          sortOrder: 3,
          tags: ['tables', 'filtering', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Multi-column filters, saved filters, bulk actions',
        },
        {
          title: 'Real backend data integration',
          description: 'Replace mock data with real backend APIs',
          status: 'todo',
          priority: 'high',
          sortOrder: 4,
          tags: ['backend', 'integration'],
        },
        {
          title: 'WebSocket for live updates',
          description: 'Implement real-time data streaming',
          status: 'todo',
          priority: 'high',
          sortOrder: 5,
          tags: ['websocket', 'realtime'],
        },
        {
          title: 'Customizable dashboard widgets',
          description: 'Allow users to configure their dashboard layout',
          status: 'todo',
          priority: 'medium',
          sortOrder: 6,
          tags: ['ux', 'customization'],
        },
        {
          title: 'Dashboard templates for different roles',
          description: 'Pre-configured dashboards for sales, marketing, support, etc.',
          status: 'todo',
          priority: 'low',
          sortOrder: 7,
          tags: ['templates', 'roles'],
        },
      ],
    },
    {
      name: 'Authentication & User Management',
      description: 'Security and user access features',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 2,
      tags: ['core', 'auth'],
      tasks: [
        {
          title: 'SSO integration for enterprise',
          description: 'SAML/OAuth SSO for enterprise customers',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['sso', 'enterprise'],
        },
        {
          title: '2FA/MFA setup UI',
          description: 'Multi-factor authentication configuration',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['security', 'mfa'],
        },
        {
          title: 'Account recovery flow polish',
          description: 'Improve password reset and account recovery UX',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['ux', 'recovery'],
        },
      ],
    },
    {
      name: 'Navigation & Search',
      description: 'Platform navigation and global search',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 3,
      tags: ['core', 'navigation'],
      tasks: [
        {
          title: 'Global search (multi-entity)',
          description: 'Search across contacts, agents, tasks, workflows with debouncing',
          status: 'done',
          priority: 'high',
          sortOrder: 1,
          tags: ['search', 'backend', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Multi-entity search with recent searches',
        },
        {
          title: 'Command palette (Cmd+K) full implementation',
          description: 'Quick actions and navigation via keyboard',
          status: 'done',
          priority: 'medium',
          sortOrder: 2,
          tags: ['ux', 'keyboard', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Command palette with recent items',
        },
        {
          title: 'Navigation history/breadcrumbs enhancement',
          description: 'Better breadcrumb trails and back navigation',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['ux', 'navigation'],
        },
        {
          title: 'Mobile navigation system',
          description: 'Bottom nav, mobile menu, swipeable lists, pull-to-refresh',
          status: 'done',
          priority: 'high',
          sortOrder: 4,
          tags: ['mobile', 'ux', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Full mobile UX suite',
        },
        {
          title: 'Notification center & toast system',
          description: 'Toast notifications and notification center with badges',
          status: 'done',
          priority: 'high',
          sortOrder: 5,
          tags: ['notifications', 'ui', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Toast + notification center + push util',
        },
      ],
    },
    {
      name: 'Settings & Configuration',
      description: 'Platform settings and preferences',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 4,
      tags: ['core', 'settings'],
      tasks: [
        {
          title: 'Team member invitations',
          description: 'Invite users to workspace with role assignment',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['team', 'invitations'],
        },
        {
          title: 'Role-based permissions UI',
          description: 'Configure granular permissions for users',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['permissions', 'rbac'],
        },
        {
          title: 'Billing & subscription management',
          description: 'Stripe integration for subscription handling',
          status: 'todo',
          priority: 'high',
          sortOrder: 3,
          tags: ['billing', 'stripe'],
        },
        {
          title: 'API keys management',
          description: 'Generate and manage API keys for developers',
          status: 'done',
          priority: 'medium',
          sortOrder: 4,
          tags: ['api', 'security', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint',
        },
        {
          title: 'Webhooks configuration',
          description: 'Configure webhooks for external integrations',
          status: 'done',
          priority: 'medium',
          sortOrder: 5,
          tags: ['webhooks', 'integration', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Full CRUD, test endpoint, HMAC signatures',
        },
        {
          title: 'Notification preferences',
          description: 'Customize email and in-app notifications',
          status: 'done',
          priority: 'low',
          sortOrder: 6,
          tags: ['notifications', 'preferences', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Granular controls, quiet hours, frequency',
        },
        {
          title: 'Appearance/theme customization',
          description: 'Custom themes and branding options',
          status: 'done',
          priority: 'low',
          sortOrder: 7,
          tags: ['ui', 'themes', 'phase-1'],
          notes: 'Completed in Phase 1 Quick Wins Sprint - Light/Dark/System, accent colors, font sizes',
        },
      ],
    },
    {
      name: 'Onboarding',
      description: 'User onboarding experience',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 5,
      tags: ['core', 'onboarding'],
      tasks: [
        {
          title: 'Real OAuth connection flows',
          description: 'Replace simulated OAuth with real integrations',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['oauth', 'integration'],
        },
        {
          title: 'Onboarding checklist persistence',
          description: 'Save and track onboarding progress',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['ux', 'persistence'],
        },
        {
          title: 'Post-onboarding guided tour',
          description: 'Interactive tour of key features',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['ux', 'tour'],
        },
      ],
    },
    {
      name: 'Activity Feed',
      description: 'Platform-wide activity tracking',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 6,
      tags: ['core', 'activity'],
      tasks: [
        {
          title: 'Complete activity feed implementation',
          description: 'Full activity tracking across all modules',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['backend', 'tracking'],
        },
        {
          title: 'Real-time activity updates',
          description: 'Live activity stream with WebSocket',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['realtime', 'websocket'],
        },
        {
          title: 'Activity filtering by type',
          description: 'Filter activities by category and user',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['filtering', 'ux'],
        },
        {
          title: 'Activity search',
          description: 'Search historical activity records',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['search'],
        },
        {
          title: 'Activity export',
          description: 'Export activity logs to CSV/PDF',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['export', 'reporting'],
        },
      ],
    },
    {
      name: 'Conversations Platform',
      description: 'Unified messaging and communications hub',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 7,
      tags: ['core', 'conversations'],
      tasks: [
        {
          title: 'Full conversation history',
          description: 'Complete message threading and history',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['backend', 'history'],
        },
        {
          title: 'Real-time messaging',
          description: 'Live message delivery with WebSocket',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['realtime', 'messaging'],
        },
        {
          title: 'Thread support',
          description: 'Nested conversation threads',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['threads', 'ux'],
        },
        {
          title: 'File attachments',
          description: 'Upload and share files in conversations',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['files', 'attachments'],
        },
        {
          title: 'Voice message support',
          description: 'Record and playback voice messages',
          status: 'todo',
          priority: 'medium',
          sortOrder: 5,
          tags: ['voice', 'audio'],
        },
        {
          title: 'Conversation search',
          description: 'Search across all conversations',
          status: 'todo',
          priority: 'low',
          sortOrder: 6,
          tags: ['search'],
        },
        {
          title: 'Conversation archiving',
          description: 'Archive old conversations',
          status: 'todo',
          priority: 'low',
          sortOrder: 7,
          tags: ['archiving', 'cleanup'],
        },
      ],
    },
    {
      name: 'Agents Dashboard',
      description: 'Agent creation and management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 8,
      tags: ['core', 'agents'],
      tasks: [
        {
          title: 'Agent creation wizard',
          description: 'Step-by-step agent creation flow',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['wizard', 'ux'],
        },
        {
          title: 'Agent marketplace',
          description: 'Browse and install pre-built agents',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['marketplace', 'templates'],
        },
        {
          title: 'Agent performance analytics',
          description: 'Track agent execution metrics and success rates',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['analytics', 'performance'],
        },
        {
          title: 'Agent testing sandbox',
          description: 'Test agents in isolated environment',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['testing', 'sandbox'],
        },
      ],
    },

    // CONTENT & MARKETING FEATURES
    {
      name: 'Blog Posts Management',
      description: 'Blog publishing and management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 9,
      tags: ['content', 'blog'],
      tasks: [
        {
          title: 'Scheduled publishing UI',
          description: 'Schedule posts for future publication',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['scheduling', 'publishing'],
        },
        {
          title: 'Post collaboration (multiple authors)',
          description: 'Multi-author editing and approval workflow',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['collaboration', 'workflow'],
        },
        {
          title: 'Version history UI',
          description: 'View and restore previous versions',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['versioning', 'history'],
        },
      ],
    },
    {
      name: 'Marketing Dashboard',
      description: 'Campaign tracking and ROI analysis',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 10,
      tags: ['content', 'marketing'],
      tasks: [
        {
          title: 'Real campaign execution integration',
          description: 'Execute campaigns across channels',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['campaigns', 'execution'],
        },
        {
          title: 'A/B testing tools',
          description: 'Create and analyze A/B tests',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['testing', 'optimization'],
        },
        {
          title: 'Attribution modeling',
          description: 'Track customer journey and attribution',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['attribution', 'analytics'],
        },
      ],
    },
    {
      name: 'Marketing Automation',
      description: 'Email, SMS, and social campaigns',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 11,
      tags: ['content', 'automation'],
      tasks: [
        {
          title: 'Email campaign builder',
          description: 'Drag-and-drop email builder',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['email', 'builder'],
        },
        {
          title: 'SMS campaign builder',
          description: 'SMS campaign creation and scheduling',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['sms', 'campaigns'],
        },
        {
          title: 'Social media post scheduler',
          description: 'Schedule posts across social platforms',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['social', 'scheduling'],
        },
        {
          title: 'Campaign templates library',
          description: 'Pre-built campaign templates',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['templates', 'library'],
        },
      ],
    },
    {
      name: 'Analytics & Insights',
      description: 'Content performance analytics',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 12,
      tags: ['content', 'analytics'],
      tasks: [
        {
          title: 'Real-time analytics updates',
          description: 'Live analytics with WebSocket',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['realtime', 'analytics'],
        },
        {
          title: 'Custom report builder',
          description: 'Build custom analytics reports',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['reports', 'customization'],
        },
        {
          title: 'Analytics export',
          description: 'Export analytics data to CSV/Excel',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['export', 'data'],
        },
      ],
    },

    // AGENT ORCHESTRATION FEATURES
    {
      name: 'Agent Teams',
      description: 'Multi-agent team coordination',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 13,
      tags: ['orchestration', 'teams'],
      tasks: [
        {
          title: 'Team performance analytics deep dive',
          description: 'Detailed metrics on team execution',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['analytics', 'performance'],
        },
        {
          title: 'Team collaboration insights',
          description: 'Analyze how agents work together',
          status: 'todo',
          priority: 'low',
          sortOrder: 2,
          tags: ['insights', 'collaboration'],
        },
      ],
    },
    {
      name: 'Workflows',
      description: 'Visual workflow builder and execution',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 14,
      tags: ['orchestration', 'workflows'],
      tasks: [
        {
          title: 'Workflow versioning',
          description: 'Version control for workflows',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['versioning', 'git'],
        },
        {
          title: 'Workflow marketplace',
          description: 'Share and discover workflows',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['marketplace', 'sharing'],
        },
        {
          title: 'Advanced condition builder',
          description: 'Complex conditional logic for workflows',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['conditions', 'logic'],
        },
      ],
    },
    {
      name: 'Approvals & Autonomy',
      description: 'Approval workflows and autonomy management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 15,
      tags: ['orchestration', 'approvals'],
      tasks: [
        {
          title: 'Custom approval rules builder',
          description: 'Define custom approval conditions',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['rules', 'customization'],
        },
        {
          title: 'Approval delegation',
          description: 'Delegate approvals to other users',
          status: 'todo',
          priority: 'low',
          sortOrder: 2,
          tags: ['delegation', 'workflow'],
        },
      ],
    },
    {
      name: 'Agent Memory System',
      description: 'Agent memory storage and retrieval',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 16,
      tags: ['orchestration', 'memory'],
      tasks: [
        {
          title: 'Memory visualization UI',
          description: 'Visual representation of agent memory',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['ui', 'visualization'],
        },
        {
          title: 'Memory search interface',
          description: 'Search across agent memories',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['search', 'ui'],
        },
        {
          title: 'Memory pruning configuration',
          description: 'Configure memory retention policies',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['configuration', 'cleanup'],
        },
      ],
    },
    {
      name: 'Message Bus',
      description: 'Inter-agent communication infrastructure',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 17,
      tags: ['orchestration', 'messaging'],
      tasks: [
        {
          title: 'Message bus monitoring UI',
          description: 'Monitor message flow and health',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['monitoring', 'ui'],
        },
        {
          title: 'Message debugging tools',
          description: 'Debug and trace messages',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['debugging', 'tools'],
        },
        {
          title: 'Message replay functionality',
          description: 'Replay messages for testing',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['replay', 'testing'],
        },
      ],
    },
    {
      name: 'Neptune AI Integration',
      description: 'AI-powered orchestration assistant',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 18,
      tags: ['orchestration', 'ai'],
      tasks: [
        {
          title: 'Voice commands for orchestration',
          description: 'Control agents via voice commands',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['voice', 'ai'],
        },
        {
          title: 'Orchestration suggestions',
          description: 'AI-powered workflow suggestions',
          status: 'todo',
          priority: 'low',
          sortOrder: 2,
          tags: ['ai', 'suggestions'],
        },
        {
          title: 'Proactive automation recommendations',
          description: 'Suggest automation opportunities',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['ai', 'proactive'],
        },
      ],
    },

    // CRM & SALES FEATURES
    {
      name: 'CRM Dashboard',
      description: 'Customer relationship management hub',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 19,
      tags: ['crm', 'dashboard'],
      tasks: [
        {
          title: 'Real CRM database integration',
          description: 'Replace mock data with real database',
          status: 'done',
          priority: 'urgent',
          sortOrder: 1,
          tags: ['backend', 'database', 'phase-2'],
          notes: 'Completed in Phase 2 - CRM page fetches from real DB',
        },
        {
          title: 'Contact creation/edit forms',
          description: 'Complete CRUD forms for contacts',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['forms', 'crud', 'phase-2'],
          notes: 'Completed in Phase 2 - ContactDialog.tsx with react-hook-form + Zod',
        },
        {
          title: 'Deal creation/edit forms',
          description: 'Complete CRUD forms for deals',
          status: 'done',
          priority: 'high',
          sortOrder: 3,
          tags: ['forms', 'crud', 'phase-2'],
          notes: 'Completed in Phase 2 - DealDialog.tsx with react-hook-form + Zod',
        },
        {
          title: 'Custom fields',
          description: 'Define custom fields for contacts and deals',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['customization', 'fields'],
        },
        {
          title: 'Contact import/export',
          description: 'Bulk import/export contacts via CSV',
          status: 'done',
          priority: 'medium',
          sortOrder: 5,
          tags: ['import', 'export', 'sprint-1'],
          notes: 'Completed - ImportContactsDialog with drag-drop, /api/crm/contacts/import and /export endpoints',
        },
        {
          title: 'Email sync integration',
          description: 'Sync emails with contacts',
          status: 'todo',
          priority: 'medium',
          sortOrder: 6,
          tags: ['email', 'sync'],
        },
        {
          title: 'Calendar sync integration',
          description: 'Sync calendar with activities',
          status: 'todo',
          priority: 'medium',
          sortOrder: 7,
          tags: ['calendar', 'sync'],
        },
        {
          title: 'Activity timeline',
          description: 'Complete timeline of contact interactions',
          status: 'todo',
          priority: 'low',
          sortOrder: 8,
          tags: ['timeline', 'history'],
        },
      ],
    },
    {
      name: 'Contacts Management',
      description: 'Contact database and enrichment',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 20,
      tags: ['crm', 'contacts'],
      tasks: [
        {
          title: 'Contact CRUD operations',
          description: 'Complete create, read, update, delete for contacts',
          status: 'done',
          priority: 'urgent',
          sortOrder: 1,
          tags: ['crud', 'backend', 'phase-2'],
          notes: 'Completed - /api/crm/contacts/[id]/route.ts with GET/PUT/DELETE',
        },
        {
          title: 'Contact detail view',
          description: 'Full contact detail page with all info',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['ui', 'details', 'phase-2'],
          notes: 'Completed - ContactDetailView.tsx component',
        },
        {
          title: 'Contact merge functionality',
          description: 'Merge duplicate contacts',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['deduplication', 'merge'],
        },
        {
          title: 'Contact segmentation',
          description: 'Segment contacts by criteria',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['segmentation', 'filtering'],
        },
        {
          title: 'Contact enrichment',
          description: 'Auto-enrich contact data from external sources',
          status: 'todo',
          priority: 'medium',
          sortOrder: 5,
          tags: ['enrichment', 'api'],
        },
        {
          title: 'Contact notes/tasks',
          description: 'Add notes and tasks to contacts',
          status: 'todo',
          priority: 'low',
          sortOrder: 6,
          tags: ['notes', 'tasks'],
        },
      ],
    },
    {
      name: 'Deals Pipeline',
      description: 'Sales pipeline management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 21,
      tags: ['crm', 'sales'],
      tasks: [
        {
          title: 'Deal CRUD operations',
          description: 'Complete create, read, update, delete for deals',
          status: 'done',
          priority: 'urgent',
          sortOrder: 1,
          tags: ['crud', 'backend', 'phase-2'],
          notes: 'Completed - /api/crm/deals/[id]/route.ts with GET/PUT/DELETE/PATCH',
        },
        {
          title: 'Deal stage management',
          description: 'Move deals through pipeline stages',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['pipeline', 'stages', 'phase-2'],
          notes: 'Completed - SalesKanban.tsx with @dnd-kit drag-and-drop',
        },
        {
          title: 'Deal probability scoring',
          description: 'AI-powered deal win probability',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['ai', 'scoring'],
        },
        {
          title: 'Deal forecasting',
          description: 'Revenue forecasting from pipeline',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['forecasting', 'analytics'],
        },
        {
          title: 'Pipeline customization',
          description: 'Customize pipeline stages and fields',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['customization', 'pipeline'],
        },
        {
          title: 'Win/loss analysis',
          description: 'Analyze why deals are won or lost',
          status: 'todo',
          priority: 'low',
          sortOrder: 6,
          tags: ['analytics', 'insights'],
        },
      ],
    },
    {
      name: 'Lead Qualification',
      description: 'Lead scoring and routing',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 22,
      tags: ['crm', 'leads'],
      tasks: [
        {
          title: 'Lead scoring rules engine',
          description: 'Configure lead scoring criteria',
          status: 'done',
          priority: 'high',
          sortOrder: 1,
          tags: ['scoring', 'rules', 'sprint-1'],
          notes: 'Completed - LeadScoringRulesDialog, /api/crm/scoring-rules CRUD, dynamic scoring engine',
        },
        {
          title: 'Lead routing automation',
          description: 'Auto-assign leads based on rules',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['routing', 'automation', 'sprint-1'],
          notes: 'Completed - LeadRoutingRulesDialog, /api/crm/routing-rules CRUD, round-robin support',
        },
        {
          title: 'Lead source tracking',
          description: 'Track where leads come from',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['tracking', 'attribution'],
        },
        {
          title: 'Lead nurturing sequences',
          description: 'Automated email sequences for leads',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['nurturing', 'email'],
        },
        {
          title: 'Lead qualification forms',
          description: 'Web forms for lead capture',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['forms', 'capture'],
        },
      ],
    },
    {
      name: 'Sales Analytics',
      description: 'Sales performance tracking',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 23,
      tags: ['crm', 'analytics'],
      tasks: [
        {
          title: 'Real sales analytics',
          description: 'Replace mock data with real metrics',
          status: 'done',
          priority: 'high',
          sortOrder: 1,
          tags: ['backend', 'analytics', 'sprint-1'],
          notes: 'Completed - /api/crm/analytics with trends, InsightsTab uses real data',
        },
        {
          title: 'Revenue reports',
          description: 'Detailed revenue reporting',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['reports', 'revenue', 'sprint-1'],
          notes: 'Completed - /api/crm/reports/revenue with pipeline breakdown, trends, forecasts',
        },
        {
          title: 'Sales forecasting',
          description: 'Predict future sales',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['forecasting', 'prediction'],
        },
        {
          title: 'Team performance tracking',
          description: 'Track individual and team performance',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['performance', 'team'],
        },
        {
          title: 'Commission calculations',
          description: 'Calculate sales commissions',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['commissions', 'finance'],
        },
      ],
    },

    // FINANCE FEATURES
    {
      name: 'Finance Dashboard',
      description: 'Financial tracking and reporting',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 24,
      tags: ['finance', 'dashboard'],
      tasks: [
        {
          title: 'Revenue tracking',
          description: 'Track all revenue sources',
          status: 'done',
          priority: 'high',
          sortOrder: 1,
          tags: ['revenue', 'tracking'],
          notes: 'Completed - /api/finance/revenue/route.ts',
        },
        {
          title: 'Expense management',
          description: 'Track and categorize expenses',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['expenses', 'tracking'],
        },
        {
          title: 'Invoice generation',
          description: 'Create and send invoices',
          status: 'done',
          priority: 'high',
          sortOrder: 3,
          tags: ['invoices', 'billing'],
          notes: 'Completed - /api/finance/invoices/route.ts with Zod validation',
        },
        {
          title: 'Payment processing',
          description: 'Process payments via Stripe',
          status: 'todo',
          priority: 'high',
          sortOrder: 4,
          tags: ['payments', 'stripe'],
        },
        {
          title: 'Financial reports',
          description: 'P&L, balance sheet, cash flow reports',
          status: 'done',
          priority: 'medium',
          sortOrder: 5,
          tags: ['reports', 'accounting'],
          notes: 'Completed - /api/finance/overview/route.ts',
        },
        {
          title: 'Budget management',
          description: 'Set and track budgets',
          status: 'todo',
          priority: 'medium',
          sortOrder: 6,
          tags: ['budgets', 'planning'],
        },
        {
          title: 'Cash flow forecasting',
          description: 'Predict future cash flow',
          status: 'done',
          priority: 'low',
          sortOrder: 7,
          tags: ['forecasting', 'cashflow'],
          notes: 'Completed - /api/finance/cashflow/route.ts',
        },
      ],
    },
    {
      name: 'Finance Integrations',
      description: 'QuickBooks, Stripe, Shopify integrations',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 25,
      tags: ['finance', 'integrations'],
      tasks: [
        {
          title: 'Real QuickBooks sync',
          description: 'Bi-directional QuickBooks sync',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['quickbooks', 'sync'],
        },
        {
          title: 'Real Stripe integration',
          description: 'Full Stripe payment processing',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['stripe', 'payments'],
        },
        {
          title: 'Real Shopify integration',
          description: 'Sync orders and inventory with Shopify',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['shopify', 'ecommerce'],
        },
        {
          title: 'Transaction sync',
          description: 'Auto-sync transactions from all sources',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['transactions', 'sync'],
        },
        {
          title: 'Reconciliation tools',
          description: 'Bank reconciliation workflows',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['reconciliation', 'accounting'],
        },
      ],
    },
    {
      name: 'Finance HQ',
      description: 'Advanced financial management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 26,
      tags: ['finance', 'advanced'],
      tasks: [
        {
          title: 'Comprehensive financial dashboard',
          description: 'Executive-level financial overview',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['dashboard', 'executive'],
        },
        {
          title: 'Multi-entity support',
          description: 'Handle multiple legal entities',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['multi-entity', 'accounting'],
        },
        {
          title: 'Tax calculations',
          description: 'Automated tax calculations',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['tax', 'compliance'],
        },
        {
          title: 'Financial planning tools',
          description: 'Scenario planning and forecasting',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['planning', 'forecasting'],
        },
      ],
    },

    // KNOWLEDGE BASE FEATURES
    {
      name: 'Knowledge Base (Library)',
      description: 'Document storage and management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 27,
      tags: ['knowledge', 'documents'],
      tasks: [
        {
          title: 'Real document storage (Vercel Blob)',
          description: 'Integrate Vercel Blob for file storage',
          status: 'done',
          priority: 'high',
          sortOrder: 1,
          tags: ['storage', 'blob'],
          notes: 'Completed - /api/knowledge/upload/route.ts uses uploadFile + Vercel Blob',
        },
        {
          title: 'Document CRUD operations',
          description: 'Create, read, update, delete documents',
          status: 'done',
          priority: 'high',
          sortOrder: 2,
          tags: ['crud', 'documents'],
          notes: 'Completed - /api/knowledge/[id]/route.ts with full CRUD',
        },
        {
          title: 'Document versioning',
          description: 'Track document versions and history',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['versioning', 'history'],
        },
        {
          title: 'Document collaboration',
          description: 'Real-time collaborative editing',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['collaboration', 'realtime'],
        },
        {
          title: 'Document permissions',
          description: 'Granular access control for documents',
          status: 'todo',
          priority: 'medium',
          sortOrder: 5,
          tags: ['permissions', 'security'],
        },
        {
          title: 'Full-text search with AI',
          description: 'Semantic search across all documents',
          status: 'done',
          priority: 'medium',
          sortOrder: 6,
          tags: ['search', 'ai'],
          notes: 'Completed - /api/knowledge/search/route.ts with vector indexing',
        },
        {
          title: 'RAG integration for Q&A',
          description: 'Answer questions from document knowledge',
          status: 'todo',
          priority: 'low',
          sortOrder: 7,
          tags: ['rag', 'ai'],
        },
      ],
    },
    {
      name: 'Knowledge (New Version)',
      description: 'Knowledge graph and articles',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 28,
      tags: ['knowledge', 'graph'],
      tasks: [
        {
          title: 'Knowledge graph visualization',
          description: 'Visual representation of knowledge connections',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['visualization', 'graph'],
        },
        {
          title: 'Knowledge article creation',
          description: 'Create and edit knowledge articles',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['articles', 'editor'],
        },
        {
          title: 'Knowledge categories',
          description: 'Organize knowledge into categories',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['categories', 'organization'],
        },
        {
          title: 'Knowledge search',
          description: 'Search across knowledge base',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['search'],
        },
        {
          title: 'Knowledge recommendations',
          description: 'AI-powered content recommendations',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['ai', 'recommendations'],
        },
      ],
    },
    {
      name: 'Creator Studio',
      description: 'Document creation and sharing',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 29,
      tags: ['knowledge', 'creator'],
      tasks: [
        {
          title: 'Template library',
          description: 'Pre-built document templates',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['templates', 'library'],
        },
        {
          title: 'Collaborative editing',
          description: 'Real-time multi-user editing',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['collaboration', 'realtime'],
        },
        {
          title: 'Document analytics',
          description: 'Track document views and engagement',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['analytics', 'tracking'],
        },
        {
          title: 'Document embedding',
          description: 'Embed documents on external sites',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['embedding', 'sharing'],
        },
      ],
    },
    {
      name: 'Launchpad (Learning Hub)',
      description: 'Learning content and progress tracking',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 30,
      tags: ['knowledge', 'learning'],
      tasks: [
        {
          title: 'Interactive demos completion',
          description: 'Finish all interactive tutorials',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['demos', 'tutorials'],
        },
        {
          title: 'Learning path recommendations',
          description: 'AI-powered learning suggestions',
          status: 'todo',
          priority: 'low',
          sortOrder: 2,
          tags: ['ai', 'recommendations'],
        },
        {
          title: 'Achievement system polish',
          description: 'Gamification and achievements',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['gamification', 'achievements'],
        },
        {
          title: 'Content refresh automation',
          description: 'Auto-update learning content',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['automation', 'content'],
        },
      ],
    },

    // INTEGRATION FEATURES
    {
      name: 'Connected Apps',
      description: 'Third-party app integrations',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 31,
      tags: ['integrations', 'apps'],
      tasks: [
        {
          title: 'Real OAuth flows for all apps',
          description: 'Implement real OAuth for all integrations',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['oauth', 'auth'],
        },
        {
          title: 'Integration health monitoring',
          description: 'Monitor integration status and errors',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['monitoring', 'health'],
        },
        {
          title: 'Integration logs',
          description: 'View logs for all integration activity',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['logs', 'debugging'],
        },
        {
          title: 'Custom integrations builder',
          description: 'Build custom API integrations',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['custom', 'builder'],
        },
        {
          title: 'Webhook management',
          description: 'Configure webhooks for integrations',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['webhooks', 'api'],
        },
      ],
    },
    {
      name: 'Calendar Integration',
      description: 'Google Calendar and Outlook sync',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 32,
      tags: ['integrations', 'calendar'],
      tasks: [
        {
          title: 'Real Google Calendar sync',
          description: 'Bi-directional Google Calendar sync',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['google', 'calendar'],
        },
        {
          title: 'Real Outlook sync',
          description: 'Bi-directional Outlook calendar sync',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['outlook', 'calendar'],
        },
        {
          title: 'Calendar event creation',
          description: 'Create events from within platform',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['events', 'creation'],
        },
        {
          title: 'Meeting scheduling',
          description: 'Schedule meetings with contacts',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['meetings', 'scheduling'],
        },
        {
          title: 'Availability management',
          description: 'Manage and share availability',
          status: 'todo',
          priority: 'low',
          sortOrder: 5,
          tags: ['availability', 'scheduling'],
        },
      ],
    },
    {
      name: 'Communication (SignalWire)',
      description: 'SMS and voice communication',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 33,
      tags: ['integrations', 'communication'],
      tasks: [
        {
          title: 'Real SignalWire API integration',
          description: 'Complete SignalWire integration',
          status: 'todo',
          priority: 'urgent',
          sortOrder: 1,
          tags: ['signalwire', 'api'],
        },
        {
          title: 'SMS sending/receiving',
          description: 'Send and receive SMS messages',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['sms', 'messaging'],
        },
        {
          title: 'Voice call capabilities',
          description: 'Make and receive phone calls',
          status: 'todo',
          priority: 'high',
          sortOrder: 3,
          tags: ['voice', 'calls'],
        },
        {
          title: 'Call transcription',
          description: 'Auto-transcribe voice calls',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['transcription', 'ai'],
        },
        {
          title: 'SMS campaigns',
          description: 'Bulk SMS campaign functionality',
          status: 'todo',
          priority: 'medium',
          sortOrder: 5,
          tags: ['campaigns', 'bulk'],
        },
        {
          title: 'Call recording',
          description: 'Record and store phone calls',
          status: 'todo',
          priority: 'low',
          sortOrder: 6,
          tags: ['recording', 'storage'],
        },
      ],
    },
    {
      name: 'Email Integration',
      description: 'Gmail and Outlook email sync',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 34,
      tags: ['integrations', 'email'],
      tasks: [
        {
          title: 'Gmail sync',
          description: 'Bi-directional Gmail synchronization',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['gmail', 'sync'],
        },
        {
          title: 'Outlook sync',
          description: 'Bi-directional Outlook email sync',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['outlook', 'sync'],
        },
        {
          title: 'Email sending',
          description: 'Send emails from platform',
          status: 'todo',
          priority: 'high',
          sortOrder: 3,
          tags: ['sending', 'smtp'],
        },
        {
          title: 'Email templates',
          description: 'Pre-built email templates',
          status: 'todo',
          priority: 'medium',
          sortOrder: 4,
          tags: ['templates', 'library'],
        },
        {
          title: 'Email tracking',
          description: 'Track opens and clicks',
          status: 'todo',
          priority: 'medium',
          sortOrder: 5,
          tags: ['tracking', 'analytics'],
        },
        {
          title: 'Email sequences',
          description: 'Automated email drip campaigns',
          status: 'todo',
          priority: 'low',
          sortOrder: 6,
          tags: ['sequences', 'automation'],
        },
      ],
    },

    // SETTINGS & ADMIN FEATURES
    {
      name: 'Admin Dashboard',
      description: 'System administration and monitoring',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 35,
      tags: ['admin', 'dashboard'],
      tasks: [
        {
          title: 'System health monitoring',
          description: 'Monitor system performance and health',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['monitoring', 'health'],
        },
        {
          title: 'Usage analytics',
          description: 'Track platform usage metrics',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['analytics', 'usage'],
        },
        {
          title: 'Admin notifications',
          description: 'Critical system notifications for admins',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['notifications', 'alerts'],
        },
        {
          title: 'Audit logs UI',
          description: 'View audit trail of all actions',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['audit', 'logs'],
        },
      ],
    },
    {
      name: 'User Management',
      description: 'User roles and permissions',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 36,
      tags: ['admin', 'users'],
      tasks: [
        {
          title: 'User role assignment UI',
          description: 'Assign roles to users',
          status: 'todo',
          priority: 'high',
          sortOrder: 1,
          tags: ['roles', 'rbac'],
        },
        {
          title: 'User permissions management',
          description: 'Manage granular user permissions',
          status: 'todo',
          priority: 'high',
          sortOrder: 2,
          tags: ['permissions', 'security'],
        },
        {
          title: 'User activity logs',
          description: 'View user activity history',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['activity', 'logs'],
        },
      ],
    },
    {
      name: 'Workspace Management',
      description: 'Multi-workspace administration',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 37,
      tags: ['admin', 'workspaces'],
      tasks: [
        {
          title: 'Workspace settings UI',
          description: 'Configure workspace settings',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['settings', 'workspaces'],
        },
        {
          title: 'Workspace member invitations',
          description: 'Invite members to workspace',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['invitations', 'members'],
        },
        {
          title: 'Workspace billing',
          description: 'Per-workspace billing and subscriptions',
          status: 'todo',
          priority: 'medium',
          sortOrder: 3,
          tags: ['billing', 'stripe'],
        },
        {
          title: 'Workspace usage limits',
          description: 'Enforce usage limits per workspace',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['limits', 'quotas'],
        },
      ],
    },
    {
      name: 'Alert Badges System',
      description: 'Notification and alert system',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 38,
      tags: ['admin', 'alerts'],
      tasks: [
        {
          title: 'Alert preferences configuration',
          description: 'Configure which alerts to receive',
          status: 'todo',
          priority: 'low',
          sortOrder: 1,
          tags: ['preferences', 'configuration'],
        },
        {
          title: 'Alert digest emails',
          description: 'Send daily/weekly alert digests via email',
          status: 'todo',
          priority: 'low',
          sortOrder: 2,
          tags: ['email', 'digests'],
        },
      ],
    },
    {
      name: 'Feedback Management',
      description: 'User feedback collection and management',
      status: 'in_progress',
      targetCompletionPercent: 100,
      sortOrder: 39,
      tags: ['admin', 'feedback'],
      tasks: [
        {
          title: 'Feedback categorization',
          description: 'Categorize feedback by type',
          status: 'todo',
          priority: 'medium',
          sortOrder: 1,
          tags: ['categorization', 'organization'],
        },
        {
          title: 'Feedback prioritization',
          description: 'Prioritize feedback items',
          status: 'todo',
          priority: 'medium',
          sortOrder: 2,
          tags: ['prioritization', 'management'],
        },
        {
          title: 'Feedback response workflow',
          description: 'Respond to user feedback',
          status: 'todo',
          priority: 'low',
          sortOrder: 3,
          tags: ['workflow', 'responses'],
        },
        {
          title: 'Feedback analytics',
          description: 'Analyze feedback trends',
          status: 'todo',
          priority: 'low',
          sortOrder: 4,
          tags: ['analytics', 'insights'],
        },
      ],
    },
  ],
};
